(() => {
 const $=s=>document.querySelector(s), app=$('#app'), SAVE='yobanashi-save-v1', LAST='yobanashi-last-v1'; let save=null, toastTimer;
 try{save=JSON.parse(localStorage.getItem(SAVE))}catch{}
 const story=id=>STORIES.find(s=>s.id===id), scene=(s,id)=>s.scenes?.[id];
 const toast=msg=>{let t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2100)};
 const setSave=x=>{save=x;localStorage.setItem(SAVE,JSON.stringify(x));localStorage.setItem(LAST,x.storyId);syncResume()};
 function syncResume(){let b=$('#resume-top');if(save){b.hidden=false}else b.hidden=true}
 const routeMenus=[
  ['アリアに「私を星に返せ」と言った理由を聞く','黒い獣に埋め込まれた星を解放する','銀髪の少年の声を追う'],
  ['アリアを信じて門へ向かう','少年に百年前の記憶を尋ねる','黒い獣を仲間として迎える'],
  ['アリアに星を託す','少年と力を重ねる','星を縛る鎖を自分が引き受ける'],
  ['七つの星に世界の願いを返す','レオン自身が八つ目の星となる','全員で未来を選び直す']
 ];
 const routeTitles=['選ばれなかった夜','星紋に残った声','三人で決める未来','黒い太陽の前で'];
 function generatedRouteScene(s,route){
  const origin=scene(s,route.originId),phase=route.actions.length,id=`if-${route.originId}-${route.originChoiceIndex}-${route.actions.map(a=>a.index).join('-')||'start'}`;
  const actions=route.actions.map(a=>a.text),initial=route.originChoice.replace(/^[A-F] /,'');
  if(phase>=4){
   const final=actions[3]||'全員で未来を選び直す';
   const endingTitle=final.includes('八つ目')?'八つ目を抱く者':final.includes('託す')?'星を返す者':final.includes('鎖')?'鎖をほどく者':'選び直した未来';
   return {id,generatedRoute:true,routePhase:phase,chapter:'サイト版　別の物語',title:endingTitle,text:`黒い太陽が砕け、夜空に新しい星の道がひらく。レオンは「${final}」という答えを選び、アリアと銀髪の少年もその決断を支えた。\n\nこの未来にたどり着くまで、レオンは「${initial}」ことから始め、「${actions.slice(0,3).join('」を選び、「')}」と選び続けた。配信で記録された道とは別に、選択を重ねた先に生まれた結末。\n\n星々はそれぞれの願いを抱いて輝き、レオンたちは新しい夜明けを歩き出す。`,ending:{title:endingTitle,type:'IF END — サイト内生成ルート',mark:'IF',text:'この結末は、あなたが重ねた選択から生まれました。'}};
  }
  const chapters=[
   `「${initial}」――レオンがそう選んだ瞬間、星紋の光が道を二つに分けた。配信の記録とは違う景色がひらく。黒い獣は一歩下がり、アリアは「その選択の先を、私も見届ける」と隣に並んだ。遠くには、星喰みの門ではない見知らぬ塔が立っている。`,
   `「${actions[0]}」という選択が、塔の扉を開いた。中には百年前の記憶ではなく、まだ起きていない未来が映っている。銀髪の少年が現れ、「ここなら、あの結末を変えられる」と告げる。彼の声には、レオンが忘れていた願いが混じっていた。`,
   `「${actions[0]}」と「${actions[1]}」。二つの選択が重なり、アリアの星に新しい色が灯る。彼女は、星を救うには誰か一人が代償を払うという古い決まりを破らなければならないと話した。黒い太陽が迫るなか、三人はそれぞれの力を差し出す。`,
   `「${actions[0]}」「${actions[1]}」「${actions[2]}」。選んできた道が、黒い太陽の前でひとつにつながる。そこには星を奪う影と、鎖につながれた七つの願い。レオンは、最後の一歩をどう踏み出すか仲間に問いかけた。`
  ];
  return {id,generatedRoute:true,routePhase:phase,chapter:'サイト版　別の物語',title:routeTitles[phase],text:chapters[phase],choices:routeMenus[phase].map((text,index)=>({text,routeOption:true,index}))};
 }
 function showGeneratedRoute(id,route){const s=story(id);if(!s)return;const c=generatedRouteScene(s,route);s.scenes[c.id]=c;play(id,c.id,false,route)}
 function resume(){if(!save)return;if(save.routeState)showGeneratedRoute(save.storyId,save.routeState);else play(save.storyId,save.nodeId)}
 function progress(s,node){let current=scene(s,node);if(current?.generatedRoute){let n=current.routePhase+1;return {pct:Math.round(n/5*100),n,total:5,route:true}}let ids=Object.keys(s.scenes).filter(id=>!s.scenes[id].generatedRoute),ix=ids.indexOf(node);return {pct:Math.max(8,Math.min(100,Math.round((ix+1)/ids.length*100))),n:ix+1,total:ids.length}}
 function home(){app.innerHTML=`<section class="hero"><div><div class="eyebrow">A SMALL STORY, JUST FOR YOU</div><h1>物語を、<br><em>あなたの手で。</em></h1><p class="hero-copy">選んだ道の先に、あなただけの結末がある。<br>好きな夜に、好きなペースで。ここから物語を始めよう。</p><div class="hero-actions"><button class="button" data-scroll-stories>物語をえらぶ <span>→</span></button><button class="text-link" data-page="about">はじめての方へ　↗</button></div></div><div class="hero-art" aria-label="月の浮かぶ夜の山並み"><div class="stars"></div><div class="moon"></div><div class="hill"></div><div class="hill two"></div><div class="lantern"></div><div class="art-caption">A QUIET PLACE TO CHOOSE</div></div></section><section class="section" id="stories"><div class="section-inner"><div class="section-head"><div><div class="eyebrow">STORIES</div><h2>物語をえらぶ</h2></div><span class="section-note">選択肢で、物語の行き先が変わります。</span></div>${save&&story(save.storyId)?`<article class="continue-card"><div><div class="eyebrow">YOUR STORY IS WAITING</div><h3>「${story(save.storyId).title}」のつづき</h3><p>前回の選択から、物語を再開できます。</p></div><button class="button" data-continue>つづきを読む →</button></article>`:''}<div class="story-grid">${STORIES.map(card).join('')}</div></div></section>`}
 function card(s){let playable=s.status==='PLAYABLE';return `<article class="story-card" data-story="${s.id}" role="${playable?'button':'group'}" ${playable?'tabindex="0"':''}><div class="cover ${s.cover}"><span class="cover-label">${s.status}</span><span class="cover-mark">${s.symbol}</span></div><div class="cover-body"><div class="tags">${s.genre.split(' / ').map(x=>`<span>${x}</span>`).join(' · ')}</div><h3 class="card-title">${s.title}</h3><p class="card-desc">${s.description}</p><div class="card-meta"><span>${s.length}</span><span class="card-arrow">${playable?'PLAY STORY　↗':'COMING SOON'}</span></div></div></article>`}
 function catalog(){app.innerHTML=`<section class="catalog-page"><div class="eyebrow">THE LIBRARY</div><h1>物語の書架</h1><p class="catalog-intro">気になる物語をひとつ、選んでみてください。</p><div class="story-grid">${STORIES.map(card).join('')}</div></section>`}
 function about(){app.innerHTML=`<section class="about-page"><div class="eyebrow">A NOTE FOR YOUR FIRST NIGHT</div><div class="about-hero"><h1>あそび方</h1><p>ここでは、物語を読む速さも、選ぶ道も、あなたの自由です。<br>配信の外でも、一人ひとりの夜に物語が届く場所をつくりました。</p></div><div class="guide-grid"><article class="guide-card"><span class="guide-num">01 / READ</span><h3>物語を読む</h3><p>画面に表示される文章を、自分のペースで読み進めます。途中で休んでも大丈夫。</p></article><article class="guide-card"><span class="guide-num">02 / CHOOSE</span><h3>選択肢を選ぶ</h3><p>気になった選択肢をひとつ選びます。あなたの選択で、次に読む場面が変わります。</p></article><article class="guide-card"><span class="guide-num">03 / DISCOVER</span><h3>結末にたどり着く</h3><p>選んだ道の先に、それぞれの結末が待っています。よければ別の道も読んでみてください。</p></article></div><div class="about-section"><h2>セーブと再開</h2><p>物語を進めると、選択した場所がこの端末のブラウザに自動保存されます。トップ画面の「つづきを読む」からいつでも再開できます。「最初から読む」を選ぶと、それまでのセーブを消して物語を始め直せます。</p><div class="save-note">セーブは今お使いのブラウザ内に保存されます。別の端末やブラウザ間では共有されません。<br>配信中のギフトやコメントは必要ありません。ここでは、あなた一人で自由に物語を楽しめます。</div></div><div class="about-section"><h2>この場所について</h2><p>「夜話」は、配信で生まれたインタラクティブノベルを、リスナーがそれぞれの時間に楽しめる形にするための試作です。配信版とはちがう一人用の体験として、ギフトなしで、好きなタイミングに、何度でも選び直せます。</p></div><div style="margin-top:30px"><button class="button" data-page="home">物語をえらぶ →</button></div></section>`}
 function play(id,nodeId,reset=false,routeState=undefined){const s=story(id);if(!s||!s.scenes)return;if(reset){localStorage.removeItem(SAVE);save=null}if(routeState===undefined)routeState=save?.storyId===id?save.routeState:null;let node=nodeId||s.start;if(!scene(s,node))node=s.start;setSave({storyId:id,nodeId:node,routeState,updatedAt:Date.now()});const c=scene(s,node),p=progress(s,node),done=!!c.ending;
 app.innerHTML=`<section class="play-layout"><aside class="play-sidebar"><button class="back-link" data-page="home">← 物語一覧へ</button><div class="tiny-label">NOW PLAYING</div><h3>${s.title}</h3><div class="progress-track"><div class="progress-fill" style="width:${p.pct}%"></div></div><div class="progress-caption">${done?'ENDING':p.route?`IF ROUTE ${p.n}/${p.total}`:`SCENE ${String(p.n).padStart(2,'0')}`}</div></aside><article class="play-main"><div class="chapter-label">${c.chapter}</div><h1 class="scene-title">${c.title}</h1><div class="scene-text">${c.text}</div>${done?`<div class="ending-box"><div class="ending-mark">${c.ending.mark}</div><div class="ending-type">${c.ending.type}</div><h2>${c.ending.title}</h2><p>${c.ending.text}</p></div><div class="ending-actions"><button class="button" data-restart="${id}">最初から読む　↺</button><button class="button secondary" data-page="home">物語一覧へ　→</button></div>`:`<div class="record-note">「配信で選択」は当日の記録ルートです。それ以外の選択は、ここから独立したサイト版IFルートになり、さらに4回選んで別のエンディングを目指します。文章はサイト内で生成するため、ギフト・追加料金・外部AIは使いません。</div><div class="choices">${c.choices.map((x,i)=>`<button class="choice" data-choice-index="${i}"><span class="choice-text">${x.text}</span>${x.recorded?'<span class="recorded-tag">配信で選択</span>':''}<span style="margin-left:auto;color:var(--green)">→</span></button>`).join('')}</div><div class="play-tools"><span class="save-state">✓ 自動セーブ済み</span><button class="tool-button" data-restart="${id}">最初から読む</button></div>`}</article><div class="side-ornament">YOUR CHOICE WRITES THE NIGHT</div></section>`;window.scrollTo({top:0,behavior:'smooth'});app.focus()}
 document.addEventListener('click',e=>{let el=e.target.closest('[data-page]');if(el){el.dataset.page==='about'?about():home();window.scrollTo(0,0);return}el=e.target.closest('[data-story]');if(el){let s=story(el.dataset.story);if(s.status==='PLAYABLE')play(s.id,save?.storyId===s.id&&!save.routeState?save.nodeId:s.start);else toast('この物語は準備中です');return}el=e.target.closest('[data-choice-index]');if(el&&save){const s=story(save.storyId),current=scene(s,save.nodeId),index=Number(el.dataset.choiceIndex),choice=current?.choices?.[index];if(!choice)return;if(save.routeState&&choice.routeOption){const route={...save.routeState,actions:[...save.routeState.actions,{index,text:choice.text}]};showGeneratedRoute(save.storyId,route)}else if(choice.recorded)play(save.storyId,choice.to,false,null);else showGeneratedRoute(save.storyId,{originId:save.nodeId,originChoiceIndex:index,originChoice:choice.text,actions:[]});return}el=e.target.closest('[data-restart]');if(el){play(el.dataset.restart,story(el.dataset.restart).start,true,null);toast('物語を最初から始めました');return}if(e.target.closest('[data-continue]')&&save){resume();return}if(e.target.closest('[data-scroll-stories]'))$('#stories').scrollIntoView({behavior:'smooth'});});document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.story-card[role="button"]')){e.preventDefault();let s=story(e.target.dataset.story);play(s.id,save?.storyId===s.id&&!save.routeState?save.nodeId:s.start)}});document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{}));$('#resume-top').addEventListener('click',resume);$('#menu-button').addEventListener('click',catalog);syncResume();home();
})();

