(() => {
 const $=s=>document.querySelector(s), app=$('#app'), SAVE='yobanashi-save-v1', LAST='yobanashi-last-v1'; let save=null, toastTimer;
 try{save=JSON.parse(localStorage.getItem(SAVE))}catch{}
 const story=id=>STORIES.find(s=>s.id===id), scene=(s,id)=>s.scenes?.[id];
 const toast=msg=>{let t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2100)};
 const setSave=x=>{save=x;localStorage.setItem(SAVE,JSON.stringify(x));localStorage.setItem(LAST,x.storyId);syncResume()};
 function syncResume(){let b=$('#resume-top');if(save){b.hidden=false}else b.hidden=true}
 function progress(s,node){let ids=Object.keys(s.scenes), ix=ids.indexOf(node);return {pct:Math.max(8,Math.min(100,Math.round((ix+1)/ids.length*100))),n:ix+1,total:ids.length}}
 function home(){app.innerHTML=`<section class="hero"><div><div class="eyebrow">A SMALL STORY, JUST FOR YOU</div><h1>物語を、<br><em>あなたの手で。</em></h1><p class="hero-copy">選んだ道の先に、あなただけの結末がある。<br>好きな夜に、好きなペースで。ここから物語を始めよう。</p><div class="hero-actions"><button class="button" data-scroll-stories>物語をえらぶ <span>→</span></button><button class="text-link" data-page="about">はじめての方へ　↗</button></div></div><div class="hero-art" aria-label="月の浮かぶ夜の山並み"><div class="stars"></div><div class="moon"></div><div class="hill"></div><div class="hill two"></div><div class="lantern"></div><div class="art-caption">A QUIET PLACE TO CHOOSE</div></div></section><section class="section" id="stories"><div class="section-inner"><div class="section-head"><div><div class="eyebrow">STORIES</div><h2>物語をえらぶ</h2></div><span class="section-note">選択肢で、物語の行き先が変わります。</span></div>${save&&story(save.storyId)?`<article class="continue-card"><div><div class="eyebrow">YOUR STORY IS WAITING</div><h3>「${story(save.storyId).title}」のつづき</h3><p>前回の選択から、物語を再開できます。</p></div><button class="button" data-continue>つづきを読む →</button></article>`:''}<div class="story-grid">${STORIES.map(card).join('')}</div></div></section>`}
 function card(s){let playable=s.status==='PLAYABLE';return `<article class="story-card" data-story="${s.id}" role="${playable?'button':'group'}" ${playable?'tabindex="0"':''}><div class="cover ${s.cover}"><span class="cover-label">${s.status}</span><span class="cover-mark">${s.symbol}</span></div><div class="cover-body"><div class="tags">${s.genre.split(' / ').map(x=>`<span>${x}</span>`).join(' · ')}</div><h3 class="card-title">${s.title}</h3><p class="card-desc">${s.description}</p><div class="card-meta"><span>${s.length}</span><span class="card-arrow">${playable?'PLAY STORY　↗':'COMING SOON'}</span></div></div></article>`}
 function catalog(){app.innerHTML=`<section class="catalog-page"><div class="eyebrow">THE LIBRARY</div><h1>物語の書架</h1><p class="catalog-intro">気になる物語をひとつ、選んでみてください。</p><div class="story-grid">${STORIES.map(card).join('')}</div></section>`}
 function about(){app.innerHTML=`<section class="about-page"><div class="eyebrow">A NOTE FOR YOUR FIRST NIGHT</div><div class="about-hero"><h1>あそび方</h1><p>ここでは、物語を読む速さも、選ぶ道も、あなたの自由です。<br>配信の外でも、一人ひとりの夜に物語が届く場所をつくりました。</p></div><div class="guide-grid"><article class="guide-card"><span class="guide-num">01 / READ</span><h3>物語を読む</h3><p>画面に表示される文章を、自分のペースで読み進めます。途中で休んでも大丈夫。</p></article><article class="guide-card"><span class="guide-num">02 / CHOOSE</span><h3>選択肢を選ぶ</h3><p>気になった選択肢をひとつ選びます。あなたの選択で、次に読む場面が変わります。</p></article><article class="guide-card"><span class="guide-num">03 / DISCOVER</span><h3>結末にたどり着く</h3><p>選んだ道の先に、それぞれの結末が待っています。よければ別の道も読んでみてください。</p></article></div><div class="about-section"><h2>セーブと再開</h2><p>物語を進めると、選択した場所がこの端末のブラウザに自動保存されます。トップ画面の「つづきを読む」からいつでも再開できます。「最初から読む」を選ぶと、それまでのセーブを消して物語を始め直せます。</p><div class="save-note">セーブは今お使いのブラウザ内に保存されます。別の端末やブラウザ間では共有されません。<br>配信中のギフトやコメントは必要ありません。ここでは、あなた一人で自由に物語を楽しめます。</div></div><div class="about-section"><h2>この場所について</h2><p>「夜話」は、配信で生まれたインタラクティブノベルを、リスナーがそれぞれの時間に楽しめる形にするための試作です。配信版とはちがう一人用の体験として、ギフトなしで、好きなタイミングに、何度でも選び直せます。</p></div><div style="margin-top:30px"><button class="button" data-page="home">物語をえらぶ →</button></div></section>`}
 function play(id,nodeId,reset=false){const s=story(id);if(!s||!s.scenes)return;if(reset){localStorage.removeItem(SAVE);save=null}let node=nodeId||s.start;if(!scene(s,node))node=s.start;setSave({storyId:id,nodeId:node,updatedAt:Date.now()});const c=scene(s,node),p=progress(s,node),done=!!c.ending;
 app.innerHTML=`<section class="play-layout"><aside class="play-sidebar"><button class="back-link" data-page="home">← 物語一覧へ</button><div class="tiny-label">NOW PLAYING</div><h3>${s.title}</h3><div class="progress-track"><div class="progress-fill" style="width:${p.pct}%"></div></div><div class="progress-caption">${done?'ENDING':`SCENE ${String(p.n).padStart(2,'0')}`}</div></aside><article class="play-main"><div class="chapter-label">${c.chapter}</div><h1 class="scene-title">${c.title}</h1><div class="scene-text">${c.text}</div>${done?`<div class="ending-box"><div class="ending-mark">${c.ending.mark}</div><div class="ending-type">${c.ending.type}</div><h2>${c.ending.title}</h2><p>${c.ending.text}</p></div><div class="ending-actions"><button class="button" data-restart="${id}">最初から読む　↺</button><button class="button secondary" data-page="home">物語一覧へ　→</button></div>`:`<div class="record-note">「配信で選択」は当日のログに記録された選択です。ほかの選択肢は表示内容を再現していますが、その後の展開はログに残っていないため、選ぶと未記録の分岐で止まります。🎁の項目も購入不要で選べます。</div><div class="choices">${c.choices.map((x,i)=>`<button class="choice" data-choice="${x.to}"><span class="choice-text">${x.text}</span>${x.recorded?'<span class="recorded-tag">配信で選択</span>':''}<span style="margin-left:auto;color:var(--green)">→</span></button>`).join('')}</div><div class="play-tools"><span class="save-state">✓ 自動セーブ済み</span><button class="tool-button" data-restart="${id}">最初から読む</button></div>`}</article><div class="side-ornament">YOUR CHOICE WRITES THE NIGHT</div></section>`;window.scrollTo({top:0,behavior:'smooth'});app.focus()}
 document.addEventListener('click',e=>{let el=e.target.closest('[data-page]');if(el){el.dataset.page==='about'?about():home();window.scrollTo(0,0);return}el=e.target.closest('[data-story]');if(el){let s=story(el.dataset.story);if(s.status==='PLAYABLE')play(s.id,save?.storyId===s.id?save.nodeId:s.start);else toast('この物語は準備中です');return}el=e.target.closest('[data-choice]');if(el){play(save.storyId,el.dataset.choice);return}el=e.target.closest('[data-restart]');if(el){play(el.dataset.restart,story(el.dataset.restart).start,true);toast('物語を最初から始めました');return}if(e.target.closest('[data-continue]')&&save){play(save.storyId,save.nodeId);return}if(e.target.closest('[data-scroll-stories]'))$('#stories').scrollIntoView({behavior:'smooth'});});document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.story-card[role="button"]')){e.preventDefault();let s=story(e.target.dataset.story);play(s.id,save?.storyId===s.id?save.nodeId:s.start)}});document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{}));$('#resume-top').addEventListener('click',()=>save&&play(save.storyId,save.nodeId));$('#menu-button').addEventListener('click',catalog);syncResume();home();
})();

